name = "navsphere"
compatibility_date = "2024-11-11"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"

[env.production.vars]
GITHUB_ID = "Ov23limnNPrmsCkPuERP"
GITHUB_OWNER = "thekingcom666"
GITHUB_REPO = "DH"
GITHUB_BRANCH = "main"
NEXTAUTH_URL = "https://dh.dataexpresss.com/api/auth"
NEXT_PUBLIC_API_URL="https://dh.dataexpresss.com/"

